### ISSUE TITLE
OpenSourceRisk forum not allowing to create new topics

### ISSUE THREAD

**Issue by cablegui** [OpenSourceRisk/Engine#10]
Hi, Apologies if this is not the right place for this issue but I don't see where else to post this.

I signed up on the website and it says that I cannot post any topics nor allowed to comment on any of the existing topics. If its any help, I am using Internet Explorer 11 for signing into the webpage.

Could someone help?

**Comment by QuaternionRisk** [comment]
Hi cabelgui,

No problem, let us look into this today.

**Comment by QuaternionRisk** [comment]
You can try now.

**Comment by cablegui** [comment]
Works now thanks
