### ISSUE TITLE
Examples fail with "No module named 'matplotlib'"

### ISSUE THREAD

**Issue by jonathanmccarthy** [OpenSourceRisk/Engine#11]
Steps to reproduce:
1. Downloaded ORE-1.8.2.zip to PC running Windows 7 Home Premium Service Pack 1.
PC has Python 3.6.1 installed.
2. Extracted to C:\Work\ORE-1.8.2.
3. Opened a cmd shell window.
4. Navigated to C:\Work\ORE-1.8.2\Examples\Example_1
5. Executed run.py

Results:
```
C:\work\ORE-1.8.2\Examples\Example_1>run.py
Traceback (most recent call last):
File "C:\work\ORE-1.8.2\Examples\Example_1\run.py", line 5, in module
    from ore_examples_helper import OreExample
  
File "..\ore_examples_helper.py", line 7, in module
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

Note the excel spreadsheet in the same folder (Example_1.xlsm) worked fine once I updated the paths.

I tried several other examples and they have the same issue.

**Comment by jonathanmccarthy** [comment]
I resolved the issue by following the installation instructions here: https://matplotlib.org/users/installing.html

`python -m pip install -U pip setuptools
python -m pip install matplotlib`

I also had to install pandas using

`python -m pip install pandas`

Example_1 then ran successfully to completion.

You may wish to updated your installation instructions to indicate matplotlib and pandas are prerequisites.

**Comment by QuaternionRisk** [comment]
Thanks Jonathan,

You don't need mathplot lib to run the examples, but it is required to generate the graphs, we do say in the user guide to install Anaconda python as this has all the required modules to make it easier, but you are correct, we don't explicitly cover the case where someone has python, but not the modules, already installed. Thanks.
