### ISSUE TITLE
Indexing object in a fixed leg of a swap doesn't work when ccy pair has to be derived with triangulation

### ISSUE THREAD

**Issue by noonediesalone** [OpenSourceRisk/Engine#110]
In release 1.8.6.0 this scenario used to work.

With current head of master now we get:
```
market object FXSpot(INRJPY) required for configuration 'default'
not found, do nothing
market object FXSpot(JPYINR) required for configuration 'default'
not found, do nothing
StructuredErrorMessage { "errorType":"Trade", "tradeId":"NonDeliverableSwap", "tradeType":"Swap", "exceptionType":"Error building trade for context 'oreapp'", "exceptionMessage":"did not find object INRJPY of type fx index under configuration 'default' or 'default'"}
```
Note that we have both EURINR and EURJPY and INRJPY fx spot should be given by triangulation.

Can provide additional details if necessary.

**Comment by noonediesalone** [comment]
Hi @pcaspers ,

Please find replication package in here [ISSUE_110.zip](https://github.com/OpenSourceRisk/Engine/files/9184870/ISSUE_110.zip)
Struggled a bit to get this content to it's minimum, so please let me know if anything is missing.
Alert message is in `output/log.txt` when run from master and in `output/npv.csv` is the proof it worked in latest release.

Regards, Laurentiu.

**Comment by pcaspers** [comment]
Thanks I'll take a look. Give me a few days though...

**Comment by pcaspers** [comment]
@noonediesalone I can reproduce the issue from our current master branch. Can I ask you to set

		<Parameter name="lazyMarketBuilding">false</Parameter>

I am pretty sure the issue has to do with this setting and some extensions around fx indices we did in the meantime.

However, when I set the flag to false, other config errors show up (ESTR curve id does not match todaysmarket-mapping, no conventions for INR-XEUIN-ZERO-CONVENTIONS, possibly more). Would it possible for you to fix the config so that we (hopefully) get a clean run as a reference? Thanks!

**Comment by pcaspers** [comment]
Internal dev ticket: https://jira.acadiasoft.net/browse/QPR-11094

**Comment by noonediesalone** [comment]
Thank you @pcaspers for taking the time.
I can confirm this flag fixed the issue. For reference, please have the attached package which now prices correctly after toggling the flag
[ISSUE_110.zip](https://github.com/OpenSourceRisk/Engine/files/9252376/ISSUE_110.zip)
.

**Comment by pcaspers** [comment]
Perfect, thank you. We will look into this to make the flag working again.

**Comment by QuaternionRisk** [comment]
This is resolved in master, closing the issue.
