### ISSUE TITLE
cashflow report discount factor is not aligned with NPV

### ISSUE THREAD

**Issue by marekkolman** [OpenSourceRisk/Engine#113]
I've noticed that the `DiscountFactor` column in the cash-flow report (typically `flows.csv`) doesn't in specific cases display values that are expected. It appears to me that the populated discount factor in `flows.csv` is based on the `DiscountingCurves` curves defined in `todaysmarket.csv` rather than the true discount factor.

To see this, let's use Example 18:

1. Run the example with the standard settings. NPV of `Trade id="Bond_Fixed"` is `11415374`. Summing all discounted cash-flows of this bond in `flows.csv` gives also `11415374`.
2. Now go to `portfolio.xml` and for `Trade id="Bond_Fixed"` change `ReferenceCurveId` from `EUR-EURIBOR-6M` to e.g. `BOND_YIELD_EUR`. In `npv.csv` the NPV of this bond is `10894231` but in `flows.csv` adding up the discounted cash-flows still (incorrectly) gives `11415374`.

Hence, the `DiscountFactor` used in `flows.csv` doesn't reflect the true discounting rate for NPV.

Can someone please check this?

**Comment by pcaspers** [comment]
This was fixed under https://jira.acadiasoft.net/browse/QPR-9315 and is already in GitHub master (but not in the latest release 1.8.6.1)
