### ISSUE TITLE
Visual Studio build error due to fxspot.*pp in project files

### ISSUE THREAD

**Issue by gbfredrik** [OpenSourceRisk/Engine#115]
Hi all,
I just want to flag that the current copy fails to build in VS because of the recent rework of FX spots in _OREData/marketdata_. The files are still listed in the project files (and filters) and need to be removed for a successful build. Let me know if you have this in check already, otherwise I can send a quick PR to clean it up.

**Comment by pcaspers** [comment]
Hi Fredrik, we already fixed that, I just pushed this and a few other updates to GitHub.
Many thanks!
Peter

**Comment by gbfredrik** [comment]
Great, thanks!
