### ISSUE TITLE
LGM discount bond option

### ISSUE THREAD

**Issue by jmelo11** [OpenSourceRisk/Engine#117]
Hi to all, 

I was looking at the LGM ZCO formula:

![image](https://user-images.githubusercontent.com/30101675/191358483-03a8a5a2-b1e4-468d-a577-fc785f48a692.png)

where small t represents the start of the zero cupon bond, but in the implemetation we see (lgm.hpp):

`Real sigma = std::sqrt(parametrization_->zeta(t)) * (parametrization_->H(T) - parametrization_->H(S));`

**Question: Shouldn't it be zeta(S) instead of zeta(t)?**

**Comment by pcaspers** [comment]
please check out the comment right before that code line
```    
    // slight generalization of Lichters, Stamm, Gallagher 11.2.1
    // with t < S, SSRN: https://ssrn.com/abstract=2246054
```

**Comment by jmelo11** [comment]
Yes! Thanks for the awnser and sorry, I didn't notice the comment!
