### ISSUE TITLE
userguide missing items

### ISSUE THREAD

**Issue by rkapl123** [OpenSourceRisk/Engine#12]
I've seen that there are 2 missing items in the userguide:
1) in section 7.3.2 Leg Data and Notionals, the elements FXReset and Exchanges with subelements 
- ForeignCurrency, ForeignAmount, FXIndex and FixingDays for FXReset and 
- NotionalInitialExchange, NotionalFinalExchange and NotionalAmortizingExchange (this element is also missing in the instruments.xsd Schema Definition) for Exchanges
2) in section 9.16 Swaption Implied Volatility the line 
IndexTenor | An integer followed by D, W, M or Y | Underlying index tenor

**Comment by QuaternionRisk** [comment]
Thanks, we will update it for the next release.
