### ISSUE TITLE
Submodule Quantlib fetching

### ISSUE THREAD

**Issue by rkapl123** [OpenSourceRisk/Engine#120]
Hi Peter!

>With regards to the authentication, do you generally use HTTPS or SSH? The entry in >.gitmodules assumes the latter. You might try and change the entry to
>https://github.com/OpenSourceRisk/QuantLib.git
>Let me know if that works for you.
>
>Thanks
>Peter

_Originally posted by @pcaspers in https://github.com/OpenSourceRisk/Engine/issues/118#issuecomment-1261885971_

I did this and it works perfectly (both from the command line and with tortoise git). I also tried to set up ssh authentification on windows (following https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) but failed miserably. I can't even clone my own repos using ssh from github.

Maybe using https is still a better option for fetching the quantlib submodule, at least for windows users.

-regards,
Roland

**Comment by pcaspers** [comment]
Ok thanks. Do you think we should switch to the https Uri, would that make life easier?

**Comment by rkapl123** [comment]
Yes, definitely so. Unless there are serious security reasons for protecting this, I think it's a lot easier to cope with.
Regards,
Roland

**Comment by pcaspers** [comment]
ok yeah - I pushed this change to master!

**Comment by rkapl123** [comment]
Mandy thanks!
Regards, Roland
