### ISSUE TITLE
Sensitivities in Par domain for Yield/Index/Discount curves

### ISSUE THREAD

**Issue by noonediesalone** [OpenSourceRisk/Engine#125]
Hi,

I know it's documented (in Annex A.14) that `sensitivity` analytics for Yield/Index/Discount curves is done in zero rate domain.
We would like to see these computed, with same "bump and revalue" approach, in a Par domain. 

So opening this issue more as a feature request 😄 
Desire is to capture the full dependency graph of sensitivities.

As an example, let's say we have a fixed GBP vs. floating EUR swap with collateral in EUR. Then the GBP fixed leg is discounted by an `YieldCurve` defined to have a `CrossCurrency` yield segment, for example this in curveconfig: 
```
<CrossCurrency>
	<Type>Cross Currency Basis Swap</Type>
	<Quotes>
		<Quote>CC_BASIS_SWAP/BASIS_SPREAD/EUR/3M/GBP/3M/1Y</Quote>
		<Quote>CC_BASIS_SWAP/BASIS_SPREAD/EUR/3M/GBP/3M/5Y</Quote>
		<Quote>CC_BASIS_SWAP/BASIS_SPREAD/EUR/3M/GBP/3M/10Y</Quote>
		<Quote>CC_BASIS_SWAP/BASIS_SPREAD/EUR/3M/GBP/3M/30Y</Quote>
	</Quotes>
	<Conventions>GBP-XEUGB-CC_BASIS_SWAP-CONVENTIONS</Conventions>
	<DiscountCurve>ESTR</DiscountCurve>
	<SpotRate>FX/RATE/EUR/GBP</SpotRate>
	<ProjectionCurveDomestic>GBP3M</ProjectionCurveDomestic>
	<ProjectionCurveForeign>EUR3M</ProjectionCurveForeign>
</CrossCurrency>
```
We've validated that the zero rates produced in this example are very close to the zero rates we can produce from a different system. So this is very encouraging. Note that `ProjectionCurveDomestic` is set to a curve id `GBP3M` pointing to an `IndexCurve`.
But when we run sensitivity on this sample trade, we don't get a risk to `GBP3M` because that is not directly quoted on the trade, but rather should be sensitive through collateralization (e.g. applying above YieldCurve as discount, which references it).

If you're interested, we can produce a working example to demonstrate the request.

Regards,
Laurentiu.

**Comment by rolandlichters** [comment]
Hi Laurentiu,

thanks for you message/request. It triggered among others that we are releasing par sensitivity analysis in ORE with the upcoming version 9. It is in ORE's master branch on GitHub already. This isn't hot of the press, one of the elements that we have been using for years , and I am happy that we can now shovel it into the open source space. Please check it out, we are curious about your feedback and happy to discuss!

Kind regards,
Roland

**Comment by noonediesalone** [comment]
Hi Roland,

Thank you so much for making this available in such a short time!

In recent period we've been validating ORE curve bootstrap against reference system, so we're in a good position to trust the curve and validate the par sensitivity framework. 
We'll pull from master and come back in the next few days with feedback/comments.

Kind regards,
Laurentiu.

**Comment by noonediesalone** [comment]
We've tested with multi-threading `-DENABLE_SESSIONS=ON` (btw, in user guide section 4.5 is instead `-DQL_ENABLE_SESSIONS=ON`) and for unitary testing (one trade) this is not improving the performance but the opposite.
This can be easily be shown with `Example_40` by setting `<Parameter name="nThreads">10</Parameter>` and run-time is doubled.
Do you have any recommendation as to when nThreads > 1 is a good idea?

Regards,
Laurentiu.

**Comment by pcaspers** [comment]
Using multiple threads introduces additional overhead (we need to build markets for each thread separately for example). Also, the parallelisation of the valuation engine works by trade. Therefore using multiple threads only pays off only if there are sufficiently many trades in the portfolio which are sufficiently expensive to reprice.

**Comment by noonediesalone** [comment]
Hi Peter,

Thanks for confirming this, I've reached the same conclusion here. With few or easy to price trades multi threading implementation is impractical. 

Similar observation for exposure, where the cube split is done only on the trades dimension. Here in fact, the implementation is even more dramatically expensive, because it has to pre-store all the scenarios for all the grid dates and simulation paths. This leads to a huge memory consumption, even before the threads are launched. Not sure if this can be avoided though since the market processes have to evolve at least once from head to back. But usually building scenarios takes more time compared to repricing and we can only parallelized the repricing (and even more disruptive is that we have to wait for scenarios before any parallel runs).

Maybe some optimization can be archived if the simulation market is filtered based on the reduced set of trades assigned to one thread (e.g. introspect the risk factors of the batch of trade and simulate only the intersection of those and the given markets). Then we can move the process evolution within threads (and avoid the memory consumption issue and also start threads as early as possible). This will of course have redundant market simulation on various threads, but this might be acceptable after market filtering (and maybe some heuristic on how to group trades such that each partition minimizes the dependent risk factors).

Regards,
Laurentiu.
