### ISSUE TITLE
Error: User registration is currently not allowed?

### ISSUE THREAD

**Issue by fordesmith** [OpenSourceRisk/Engine#154]
Hi - I do not know where else to post this. 
"Error: User registration is currently not allowed" is the error when you try to sign up to the ORE community / forum. 
Can you point me to someone who can help with this? 
https://www.opensourcerisk.org/forum/register/
Forde

**Comment by fordesmith** [comment]
@rolandlichters can you help?

**Comment by QuaternionRisk** [comment]
Hi Forde, please try again, it should work now.

**Comment by pcaspers** [comment]
This seems to be working now? Pls reopen if you still have issues.
