### ISSUE TITLE
errors after running runCmakeVS

### ISSUE THREAD

**Issue by shreyashnadage** [OpenSourceRisk/Engine#158]
Got following error after running runCmakeVS:

"C:\Users\rutuj\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\rutuj\Engine\build\OREAnalytics\orea\OREAnalytics-x64-mt.vcxproj" (default target) (21) ->
"C:\Users\rutuj\Engine\build\OREData\ored\OREData-x64-mt.vcxproj" (default target) (22) ->
"C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj" (default target) (23) ->
(ClCompile target) ->
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,10): error C2039: 'map': is not a member of 'std' (c
ompiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\computeenvironment.cpp) [C:\Users\rutuj\Engine\build\Quant
Ext\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,13): error C2143: syntax error: missing ';' before '
<' (compiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\computeenvironment.cpp) [C:\Users\rutuj\Engine\build\
QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,13): error C4430: missing type specifier - int assum
ed. Note: C++ does not support default-int (compiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\computeenviro
nment.cpp) [C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,53): error C2238: unexpected token(s) preceding ';'
(compiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\computeenvironment.cpp) [C:\Users\rutuj\Engine\build\Qua
ntExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,10): error C2039: 'map': is not a member of 'std' (c
ompiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp) [C:\Users\rutuj\Engine\build\QuantE
xt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,13): error C2143: syntax error: missing ';' before '
<' (compiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp) [C:\Users\rutuj\Engine\build\Q
uantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,13): error C4430: missing type specifier - int assum
ed. Note: C++ does not support default-int (compiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\openclenviron
ment.cpp) [C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle/math/openclenvironment.hpp(37,53): error C2238: unexpected token(s) preceding ';'
(compiling source file C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp) [C:\Users\rutuj\Engine\build\Quan
tExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp(927,34): error C2065: 'contexts_': undeclared identifie
r [C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp(927,32): error C2059: syntax error: ':' [C:\Users\rutuj
\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp(933,14): error C2065: 'contexts_': undeclared identifie
r [C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp(934): error C3536: 'c': cannot be used before it is ini
tialized [C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]
  C:\Users\rutuj\Engine\QuantExt\qle\math\openclenvironment.cpp(934,14): error C2065: 'contexts_': undeclared identifie
r [C:\Users\rutuj\Engine\build\QuantExt\qle\QuantExt-x64-mt.vcxproj]

**Comment by rkapl123** [comment]
Hi, it seems that your installed visual studio version doesn't meet the minimum requirements for compiling ORE. What version do you use?

**Comment by shreyashnadage** [comment]
I am using Visual Studio version 17 2022. and boost version is 1_82_0.
I was able to resolve most of the errors by adding #include<map> to the opencleenvironment.cpp

**Comment by rkapl123** [comment]
OK, then I think it's probably the old problem with getting the correct ORE vs. Quantlib version.
If I correctly assume that you want to build the latest ORE version (1.8.10), then the safest way ist NOT to pull the current master (I did that initially and got a lot of errors too) but rather to switch to the tag 1.8.10:
![image](https://github.com/OpenSourceRisk/Engine/assets/7430763/fc113ee6-ed82-4189-b087-064290b7f578)
and then download the zip with the code:
![image](https://github.com/OpenSourceRisk/Engine/assets/7430763/8f103a91-78e0-42bf-9dee-5c8087dfc231)
next you got to the Quantlib version that this ORE Version was built with:
![image](https://github.com/OpenSourceRisk/Engine/assets/7430763/75676c48-a84e-470f-a9a9-aead2d0e9747)
and download the zip with the code here as well:
![image](https://github.com/OpenSourceRisk/Engine/assets/7430763/81153cb3-7be3-4b43-bb41-be18ff381612)
The last step is to integrate the Quantlib Folder into the ORE source tree:
![image](https://github.com/OpenSourceRisk/Engine/assets/7430763/a4bd0f49-3799-4765-822d-f116d5e4c7e2)
... by putting the contents of the downloaded Quantlib into the Quantlib folder...
This should build perfectly.

-regards,
Roland

**Comment by shreyashnadage** [comment]
Thanks for suggesting this. Let me try this out. I was following the new video tutorial by Alexis David.

**Comment by rkapl123** [comment]
I see, unfortunately Alexis doesn't mention that once the master moves away from the last release (tag), then there is no guarantee that the described approach using git cloning from master works anymore. Maybe the guys could add something to describe how to correctly get the ORE release tag and also the matching Quantlib subproject using git. Using TortoiseGit, this is not trivial.

Concerning your other question on the toolset version, Alexis mentioned in his other video how to find that: [https://youtu.be/NSNvOwY4mIY?list=PLb2K3onkfSic2KRNq4puugI0ZLmhmJyh7&t=296](https://youtu.be/NSNvOwY4mIY?list=PLb2K3onkfSic2KRNq4puugI0ZLmhmJyh7&t=296)

**Comment by shreyashnadage** [comment]
Thanks Roland for sharing this.

**Comment by rkapl123** [comment]
I've also added a way to get the versions from git more precisely:

git clone https://github.com/opensourcerisk/engine.git oredir
cd oredir
git checkout tags/v1.8.10.0
git submodule init
git submodule update
cd QuantLib
git checkout c235cdabbb34beaae601700092b9abfefdd7fc6a

The commit on the last line for the QuantLib submodule can always be found on the git code page as described above (just take the last part of the link).

**Comment by Timur-mur** [comment]
Hi! When trying to build runCmakeVS, I get the errors that I attached below. I took the assembly instructions on YouTube. VisualStudio version 2022, Boot - 1.82.0 14.3. What could be the problem?



"C:\Users\timurfattahov\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\timurfattahov\Engine\build\App\ore.vcxproj" (default target) (26) ->
(Target object Link) ->
  LINK : fatal error LNK1181: the input file cannot be opened "lzma.lib" [C:\Users\timurfattahov\Engine\build\App\ore.vcxproj]


"C:\Users\timurfattahov\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\timurfattahov\Engine\build\OREAnalytics\test\orea-test-suite.vcxproj" (default target) (27) ->
  LINK : fatal error LNK1181: the input file cannot be opened "lzma.lib" [C:\Users\timurfattahov\Engine\build\OREAnalytics\test\orea-test-suite.vcxproj]


"C:\Users\timurfattahov\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\timurfattahov\Engine\build\OREData\test\ored-test-suite.vcxproj" (default target) (28) ->
  LINK : fatal error LNK1104: can't open the file "libboost_system-vc143-mt-x64-1_82.lib" [C:\Users\timurfattahov\Engine\build\OREData\test\ored-test-suite.vcxproj]


"C:\Users\timurfattahov\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\timurfattahov\Engine\build\QuantExt\test\quantext-test-suite.vcxproj" (default target) (32) ->
  LINK : fatal error LNK1104: can't open the file "libboost_system-vc143-mt-x64-1_82.lib" [C:\Users\timurfattahov\Engine\build\QuantExt\test\quantext-test-suite.vcxproj]

**Comment by mgroncki** [comment]
It seems that VS can not find the boost library. 

Have you installed boost and set the enviormental variables `BOOST` and `BOOST_LIB64` pointing to the include and lib dir?

Having a recent version of Anaconda installed could cause also some troubles with the cmake configure step. Anaconda comes now with a boost library but there are not all binaries included. Often CMAKE tries to use the anaconda boost instead of the dedicated boost version. You can fix that by adding the flag `-DBoost_NO_SYSTEM_PATHS=ON` to the cmake command in runCmakeVS script:

`cmake -G "Visual Studio 17 2022" -A x64 -DBOOST_INCLUDEDIR=%BOOST% -DBOOST_LIBRARYDIR=%BOOST_LIB64% -DQL_ENABLE_SESSIONS=ON **-DBoost_NO_SYSTEM_PATHS=ON** -B build`

That should prevent cmake to look for boost in any other directories beside the hint variables -DBOOST_INCLUDEDIR and -DBOOST_LIBRARYDIR.

If you use the prebuilt boost binaries, I would recommend you to use boost 1.72 v142. Newer prebuilt version can cause some problems under windows (https://github.com/OpenSourceRisk/Engine/issues/160).

**Comment by Timur-mur** [comment]
Everything is gathered! I had to use an earlier version of Anaconda. Thanks!!!
