### ISSUE TITLE
Issues while running runCmakeVS

### ISSUE THREAD

**Issue by shreyashnadage** [OpenSourceRisk/Engine#159]
I get following error while running the runCmakeVS:
"C:\Users\Admin\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Admin\Engine\build\App\ore.vcxproj" (default target) (26) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'libboost_serialization-vc143-mt-x64-1_82.lib' [C:\Users\Admin\Engine\bu
ild\App\ore.vcxproj]

"C:\Users\Admin\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Admin\Engine\build\OREAnalytics\test\orea-test-suite.vcxproj" (default target) (27) ->
  LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc143-mt-x64-1_82.lib' [C:\Users\Admin\Engine\build\ORE
Analytics\test\orea-test-suite.vcxproj]

"C:\Users\Admin\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Admin\Engine\build\OREData\test\ored-test-suite.vcxproj" (default target) (28) ->
  LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc143-mt-x64-1_82.lib' [C:\Users\Admin\Engine\build\ORE
Data\test\ored-test-suite.vcxproj]

"C:\Users\Admin\Engine\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Admin\Engine\build\QuantExt\test\quantext-test-suite.vcxproj" (default target) (32) ->
  LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc143-mt-x64-1_82.lib' [C:\Users\Admin\Engine\build\Qua
ntExt\test\quantext-test-suite.vcxproj]

Visual Studio Version info:
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.6.4

BOOST version:
boost_1_82_0

**Comment by rkapl123** [comment]
Did you download the correct Boost for your VS version?
![image](https://github.com/OpenSourceRisk/Engine/assets/7430763/744aa1f8-76c1-42e3-8c5c-d11c82f15ab4)

**Comment by shreyashnadage** [comment]
Thanks for such prompt response. I have another dumb question. How can I find which is the appropriate version of boost compatible with the visual studio version I have? Thanks again for your help. Much appreciated.

**Comment by rkapl123** [comment]
A good reference for this is [https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering), you can find the runtime library version in the last column, the toolset version (as needed by the linker looking up the libraries) can be obtained by taking the first three digits of the runtime library version and dropping the decimal, e.g. '143'.

**Comment by rkapl123** [comment]
I've wrapped the two issues in the Readme of [https://github.com/rkapl123/OREVisualStudio](https://github.com/rkapl123/OREVisualStudio).

**Comment by shreyashnadage** [comment]
You are a rockstar! Thanks I was able to build ORE successfully!
