### ISSUE TITLE
Replacing ibor reference rates with risk free rates

### ISSUE THREAD

**Issue by fordesmith** [OpenSourceRisk/Engine#166]
**Context:** Am updating the pseudo market data in the examples with real data. 

**Error:**
Error in ORE analytics: Failed to build market: Cannot build all required curves! Building failed for: (Yield/CHF/CHF3M: did not find required rfr index 'CHF-SARON' for replaced ibor index 'CHF-LIBOR-3M', is the rfr index configured in todays market parameters?); (Yield/CHF/CHF6M: did not find required rfr index 'CHF-SARON' for replaced ibor index 'CHF-LIBOR-6M', is the rfr index configured in todays market parameters?); (Yield/EUR/EUR1D: did not find required rfr index 'EUR-ESTER' for replaced ibor index 'EUR-EONIA', is the rfr index configured in todays market parameters?); 

**Method to recreate:**
Run Example_1 with updated market data and fixings and as_of date of 2020-02-25.

No changes were made to any config files other than market data, fixings and ore.xml (to point to these new files).

**Suspected source of issue:**
The need to replace Ibor reference rates by risk free rates.

**Information sought:**

_What is the process for adding required the rfr index CHF-SARON for replaced ibor index CHF-LIBOR-3/6M?_ Armed with that information, I hope to be able to replace other LIBOR dependencies. 

I have experimented with changes to conventions.xml, todaysmarket.xml and curveconfig.xml but I have not yet been able to solve it.

**Comment by noonediesalone** [comment]
The error is in the form of a question `is the rfr index configured in todays market parameters?`. 
Check your `todaysmarket.xml` and provide definition for e.g.:
```
<IndexForwardingCurves id="default">
    ...
	<Index name="CHF-SARON">Yield/CHF/CHF1D</Index>
    ...
</IndexForwardingCurves>
```
This is just the first thing that needs defined. Then you have to follow the curve definition and setup the market segments for a proper RFR curve.

**Comment by fordesmith** [comment]
Thanks @noonediesalone 

I should have explained further. I added the index "CHF-SARON" in todaysmarket.xml and changed references from CHF-LIBOR to CHF-SARON for the CHF1D Yield Curve in curveconfig.xml and from CHF-LIBOR-CONVENTIONS to CHF-SARON-CONVENTIONS (in CHF1D, CHF3M, CHF6M Yield curves). 

I assumed that I needed indices for CHF-SARON-3M and 6M (compound rates based on SARON), and proceeded as per CHF-SARON for these. 

todaysmarket.xml 
    <Index name="CHF-SARON-3M">Yield/CHF/CHF3M</Index>
    <Index name="CHF-SARON-6M">Yield/CHF/CHF6M</Index>
    <Index name="CHF-SARON">Yield/CHF/CHF1D</Index>
    
I also adjusted the CHF-3/6M-FRA-CONVENTIONS and CHF-3/6M-SWAP-CONVENTIONS to replace the pointer to CHF-LIBOR-x. 

  <FRA>
    <Id>CHF-6M-FRA-CONVENTIONS</Id>
    <Index>CHF-SARON-6M</Index>
  </FRA>
  <FRA>
    <Id>CHF-3M-FRA-CONVENTIONS</Id>
    <Index>CHF-SARON-3M</Index>
  </FRA>
  
    <Swap>
    <Id>CHF-3M-SWAP-CONVENTIONS</Id>
    <FixedCalendar>ZUB,UK</FixedCalendar>
    <FixedFrequency>Annual</FixedFrequency>
    <FixedConvention>MF</FixedConvention>
    <FixedDayCounter>30/360</FixedDayCounter>
    <Index>CHF-SARON-3M</Index>
  </Swap>
    <Swap>
    <Id>CHF-6M-SWAP-CONVENTIONS</Id>
    <FixedCalendar>ZUB,UK</FixedCalendar>
    <FixedFrequency>Annual</FixedFrequency>
    <FixedConvention>MF</FixedConvention>
    <FixedDayCounter>30/360</FixedDayCounter>
    <Index>CHF-SARON-6M</Index>
  </Swap>

Error in ORE analytics: Failed to build market: Cannot find conventions for id CHF-3M-SWAP-CONVENTIONS.

This was the point I was /am stuck.

**Comment by noonediesalone** [comment]
You're mixing things up. There's no such thing as **<Index>CHF-SARON-6M</Index>** 
SARON is overnight and has no tenor. You need to device your setup with a bit more patience and care 😄

**Comment by fordesmith** [comment]
OK, got it. I know there are forward looking term rates for e.g. SONIA, SOFR and TONAR but didn't realise there are none for SARON. 

Should I instead use the iborfallback configuration? e.g. 

<Fallbacks>
                <Fallback>
                        <IborIndex>CHF-LIBOR-3M</IborIndex>
                        <RfrIndex>CHF-SARON</RfrIndex>
                        <Spread>0.0020479999999999999</Spread>
                        <SwitchDate>2022-01-01</SwitchDate>
                </Fallback>
                <Fallback>
</Fallback>
