### ISSUE TITLE
Calcute VaR by Historical Simulation

### ISSUE THREAD

**Issue by zoo-keeper** [OpenSourceRisk/Engine#168]
hi ,
ORE now support calcute VaR by Delta gamma normal method ,  i want to know if there a way to calcute VaR by historical Simulation method , generates scenarios by applying risk factor moves  from a historical period. 

best regards, 
gavin

**Comment by rkapl123** [comment]
Not yet, there is neither the possibility to import historical scenarios nor to use it for anything like risk simulation.

-regards,
Roland

**Comment by zoo-keeper** [comment]
ok, thanks
