### ISSUE TITLE
Wrong npv settlement currency in DiscountingFxForwardEngine?

### ISSUE THREAD

**Issue by djkrystul** [OpenSourceRisk/Engine#169]
It seems that the settlement currency of npv was not changed as intended:

https://github.com/OpenSourceRisk/Engine/blob/52e775ed49a061c7d0cc5d3c33d2f92f1bcae9fd/QuantExt/qle/pricingengines/discountingfxforwardengine.cpp#L150

it should be:

`results_.npv = Money(settleCcy, results_.value);`

see definition of settleCcy:

https://github.com/OpenSourceRisk/Engine/blob/52e775ed49a061c7d0cc5d3c33d2f92f1bcae9fd/QuantExt/qle/pricingengines/discountingfxforwardengine.cpp#L92

**Comment by pcaspers** [comment]
I agree. And your suggestion is also consistent with the npvCurrency set in the trade builder.

**Comment by pcaspers** [comment]
We always populate payCcy in the fx forward instrument in the trade builder, so that the issue will not show up as long as you use the instrument via the trade builder only.

But of course it should work with an isolated instrument and pricing engine.

Would you like to open a PR for the fix?
