### ISSUE TITLE
Problem with initial installation of QuantExt with VS 2017 v.15.4

### ISSUE THREAD

**Issue by vlwagenleitner** [OpenSourceRisk/Engine#20]
Hi, please, explain how to compile QuantExt with VS 2017. There was an error C2516: "Quantext::FxForward::engine is not a legal base class"  while compiling ORE. On the other hand, Quantlib compiled without any errors in release mode under the same VS.

**Comment by QuaternionRisk** [comment]
ORE v1.8.2.0 does not work with VS 2017, we will have this fixed with the next release in the coming days (this week or next hopefully)

**Comment by QuaternionRisk** [comment]
head works with VS 2017 now
