### ISSUE TITLE
Set up VarianceSwaps

### ISSUE THREAD

**Issue by FbnRisk** [OpenSourceRisk/Engine#201]
Hi,
I am trying to set up  **VarianceSwaps** in ORE (FX and Equity). Both TradeTypes _VarianceSwap_ and _VarSwap_ appear to create the following errors: 

StructuredMessage { "category": "Error", "group": "Trade", "message": "TradeFactory::getBuilder(VarianceSwap): no builder found", "sub_fields": [ { "name": "exceptionType", "value": "Error parsing Trade XML" }, { "name": "tradeId", "value": "VarianceSwap_1" }, { "name": "tradeType", "value": "VarianceSwap" } ] }

StructuredMessage { "category": "Error", "group": "Trade", "message": "TradeFactory::getBuilder(VarSwap): no builder found", "sub_fields": [ { "name": "exceptionType", "value": "Error parsing Trade XML" }, { "name": "tradeId", "value": "VarianceSwap_2" }, { "name": "tradeType", "value": "VarSwap" } ] }

In addition, how should the PricingEngine for VarianceSwap be set up?

Regards

**Comment by pcaspers** [comment]
The trade type should be EquityVarianceSwap, FxVarianceSwap. Best, Peter
