### ISSUE TITLE
Deviations in Base NPV in Sensitivity output and NPV output

### ISSUE THREAD

**Issue by FbnRisk** [OpenSourceRisk/Engine#202]
Hi,
When creating a sensitivity file, the output "base NPV" is different to output "NPV(Base)" of the NPV file. Depending on the trade, deviations range between a few hundred euros to several million euros. In relative terms, these deviations span from 0.1% up to 40%.
Both Base PVs are in the same currency (i.e., Euro).  The trade types I am looking into are Swaps (IRS, OIS and XCCY).
This phenomen can also be observed in the provided Example 15.

Regards

**Comment by mgroncki** [comment]
Hi,

you need to add the node `<UseSpreadedTermStructures>True</UseSpreadedTermStructures>` to the sensitivity.xml. Then the baseNPV and NPV(base) should be aligned.

Its an additional flag and its described in the UserGuide in 7.5 Sensitivity Analysis: sensitivity.xml

> UseSpreadedTermStructures: If set to true, spreaded termstructures over t0 will
 be used for sensitivity calculation (where supported), to improve the alignment
 of the scenario sim market and t0 curves

**Comment by FbnRisk** [comment]
Thanks a lot for your quick response. The flag set to True aligns baseNPV and NPV(base).
