### ISSUE TITLE
Discrepancies in Interpolated Discount Curve Output

### ISSUE THREAD

**Issue by FbnRisk** [OpenSourceRisk/Engine#220]
Hello everyone,

I'm currently comparing ORE’s interpolated discount curve output against an interpolation performed with Quantlibxl. Therefore, I provided direct discount factors into ORE and created discount curve objects in Quantlibxl.

When comparing the ORE standard grid (240,1M) output against Quantlib’s "qlYieldTSDiscount" function in Excel, I've observed matching OIS curves for EUR, GBP, USD, etc., as well as tenor curves for certain currencies like AUD, CAD, EUR, and HUF.
However, I've identified discrepancies when comparing tenor curves for USD and GBP, which are leading to deviations of around >2 Bps for each month.

In detail:
- No deviation observed for: EUR OIS, EUR 1M/3M/6M, AUD OIS, AUD 3M/6M, CAD OIS, CAD 1M/3M, GBP OIS, USD OIS, HUF 3M/6M
- Deviation observed for: GBP 1M/3M/6M, USD 1M/3M/6M

Further, these deviations lead to pricing deviations between ORE and Quantlib due to a resulting for-ward mismatch.

Could someone please provide insight into potential settings or factors that might be causing these interpolation deviations?

Regards

**Comment by pcaspers** [comment]
Hi, are you using the dates from the ORE curve report as input to qlYieldTSDiscount? Can you post the curve config for GBP1M vs. the corresponding QLXL setup (rate helpers etc.)?

**Comment by FbnRisk** [comment]
Thanks for picking this up. Yes, I use the date grid of the ORE output as an input into qlYieldTSDiscount. I have attached the curve object set up via discount factors for GBP1M and GBP 1D. The same discount factors are used as explicit input into ORE (see screenshot of setup). 
[Example_GBP1M_GBP1D.xlsx](https://github.com/OpenSourceRisk/Engine/files/14212070/Example_GBP1M_GBP1D.xlsx)

**Comment by pcaspers** [comment]
Just to exclude some obvious mistakes:
- are the interpolation methods aligned (both LogLinear I presume)
- are the yield curve day counters aligned (both A365F ?)
- do you input enough decimal places in market.txt, you write 20231229 DISCOUNT/RATE/GBP/GBP1M/20251230 0.92334 as a comment in the excel where you just have 5 decimal places

**Comment by FbnRisk** [comment]
- Interpolation methods are both Loglinear (standard setting for ORE (page 129 ORE guide v11) and selected in QL (cell C8))
- Day counters: QL and ORE both use the standard setting Actual/365 (Fixed) (page 129 & 472 ORE guide v11)
- The market data input is the same for QL when building the curve object and for ORE. The input does not have more decimal numbers in both cases (e.g., cell C17 has the same value as the example market data line 20231229 DISCOUNT/RATE/GBP/GBP1M/20251230 0.92334). Also for the matching curves, the same accuracy in numbers is used (see for example GBP1D).

**Comment by pcaspers** [comment]
Thank you. Manual interpolation of the discount factor for 29.12.2025 between 29.12.2023 (discount = 1) and 30.12.2025 (discount = 0.92334) gives an interpolated discount factor that matches N39 (QL interpolation) while G39 is a little bit off.

Could you send the Input folder that you used for the ORE run? I'll have a look then. You can send the data to my private email address if that works for you.

**Comment by pcaspers** [comment]
The default behavior of ORE is to replace ceased Ibor indices with their fallback. In the case of GBP-LIBOR-1M the cessation date is 2022-01-01 and your asof date for the run is 2023-12-29. The curve report therefore contains the discount factor for the fallback curve GBP SONIA + 3.26b.

To switch off the automatic fallback you can use an iborfallbackconfig.xml and set

```
<IborFallbackConfig>
	<GlobalSettings>
		<EnableIborFallbacks>false</EnableIborFallbacks>
         ....
```

When I do this in your example, I get the same discount factor for GBP-LIBOR-1M as QLXL.

Can you check if that resolves your issue in all cases?

Best
Peter

**Comment by FbnRisk** [comment]
I compared all curves with the updated settings - no deviations. 

As a note, it is already sufficient to disable the UseRfrCurveInTodaysMarket in the iborfallbackconfig.xml file. This still enables ORE to use fallbacks but creates the tenor curves based on the provided input data: 

```
<GlobalSettings>
	<EnableIborFallbacks>true</EnableIborFallbacks>
	<UseRfrCurveInTodaysMarket>false</UseRfrCurveInTodaysMarket>
	...
```

Thanks a lot for your support to solve this puzzle. Really appreciate your quick follow up on the topic and the good guidance.
