### ISSUE TITLE
What are the plans for r12? 

### ISSUE THREAD

**Issue by vannarho-fas** [OpenSourceRisk/Engine#225]
Hi,
I noticed that updates to the user guide for release 12 were made on January 15, which aligns with the recent pattern of  three-month-ish release cycles. Could you please provide the latest updates on the release schedule and plans? Thank you.

**Comment by rolandlichters** [comment]
Hi,
we are preparing for the 12th release with new features that need internal approval. We expect the release to appear in May and then to get back to the quarterly-ish frequency. 
Best wishes,
Roland

**Comment by vannarho-fas** [comment]
Thanks Roland for the clarification

**Comment by QuaternionRisk** [comment]
I'll close this, since release 12 is out now
