### ISSUE TITLE
Custom OIS-Indices not usable

### ISSUE THREAD

**Issue by FEngelke13** [OpenSourceRisk/Engine#238]
Although the OvernightIndex node is configured and judging from the log is also loaded correctly, all subsequent conventions based on this index are not loaded.

```
  <OvernightIndex>
    <Id>CZK-CZEONIA</Id>
    <FixingCalendar>CZK</FixingCalendar>
    <DayCounter>A360</DayCounter>
    <SettlementDays>2</SettlementDays>
  </OvernightIndex>
  <OIS>
    <Id>CZK-OIS-CONVENTIONS</Id>
    <SpotLag>2</SpotLag>
    <Index>CZK-CZEONIA</Index>
    <FixedDayCounter>A360</FixedDayCounter>
    <FixedCalendar>CZK</FixedCalendar>
    <PaymentLag>1</PaymentLag>
    <EOM>True</EOM>
    <FixedFrequency>Annual</FixedFrequency>
    <FixedConvention>MF</FixedConvention>
    <FixedPaymentConvention>MF</FixedPaymentConvention>
    <Rule>Backward</Rule>
    <PaymentCalendar>CZK</PaymentCalendar>
  </OIS>
```

-----------------------------------------------------------------
DEBUG    [2024-May-22 11:46:43.600741] (...ored\configuration\conventions.cpp:2448) : Loading Convention CZK-CZEONIA
WARNING  [2024-May-22 11:46:43.609875] (...ored\configuration\conventions.cpp:2454) : Exception parsing convention XML Node (id = CZK-OIS-CONVENTIONS) : parseIborIndex "CZK-CZEONIA" not recognized

**Comment by pcaspers** [comment]
This should be fixed in the 1.0.8.12 release which will be released shortly (this month)

**Comment by pcaspers** [comment]
Could you check if the v12 release fixes your issue?

**Comment by FEngelke13** [comment]
Yes, everything works perfect now.

**Comment by pcaspers** [comment]
Thanks for confirming
