### ISSUE TITLE
Error when running make install for QuantExt 

### ISSUE THREAD

**Issue by mcraveiro** [OpenSourceRisk/Engine#25]
Hi Open Source Risk Engine devs,

Many thanks for a really useful tool. I am trying to build a development docker container with OSRE, based on an alpine image. I have successfully built QuantExt but when I try to ```make install``` it, I get an error almost at the end: 

```
make[2]: Entering directory '/home/Engine-2a56688ff4d91e378bf88620a45864824150fbc5/QuantEexactlyxt'
make[2]: Nothing to be done for 'install-exec-am'.
 config/install-sh -c -d '/usr/share'
 /usr/bin/install -c -m 644 ./config '/usr/share'
install: omitting directory './config'
make[2]: *** [Makefile:433: install-dist_dataDATA] Error 1
make[2]: Leaving directory '/home/Engine-2a56688ff4d91e378bf88620a45864824150fbc5/QuantExt'
make[1]: *** [Makefile:764: install-am] Error 2
make[1]: Leaving directory '/home/Engine-2a56688ff4d91e378bf88620a45864824150fbc5/QuantExt'
make: *** [Makefile:460: install-recursive] Error 1
```
Unfortunately, I am more familiar with CMake rather than autotools so I am yet to understand what make is trying to tell me. My theory at present is that it is attempting to install the directory ```config```, which I believe is generated by ```configure``` and should probably be skipped (the message ```install: omitting directory './config'``` is reminiscent of ```cp``` without the ```-r``` flag, when copying directories).

Any ideas of thoughts on this are greatly appreciated.

Cheers

Marco

**Comment by QuaternionRisk** [comment]
Hi Marco,

We just pushed some Docker compose scripts to /Docker that we had been starting to us. These are a bit different to the one in /tools/Docker and they should be merged (or one set deleted), but for now maybe try them out? they are layered so you have separate ones for boost, QL, ORE libs and then the app itself. I think there were some issues similar to the ones you describe around make install (which I don't run normally).

The ORE makefiles are based of the QL ones, autotools are a bit old but very portable, I would like to move to cmake at some point but that's a separate issue I think.

Try them out and see if that works.

Regards,
Niall.

**Comment by mcraveiro** [comment]
@QuaternionRisk thanks for the prompt reply. I'll have a look at your ```Dockerfile``` and see how it differs from mine - likely I am doing something wrong, as I have diffed ORE's autotools setup with QuantLib's and I can't see anything significantly different (other than a few sensible clean-ups). Interestingly, I've built QuantLib with CMake so perhaps they too have this problem; I'll check.

On the topic of CMake, I noticed that @kuangche-james has added CMake support to ORE on a fork [1], but I decided to stay with mainline as it seems his work will probably need some tidy-up before a PR can be submitted. So for now I'll just stick to autotools.

Cheers

[1] https://github.com/kuangche-james/Engine

**Comment by mcraveiro** [comment]
Right, your ```Dockerfile```[1] has indeed all the answers. You do:

```
 && ./autogen.sh \
  && ./configure --disable-static CXXFLAGS=-O2 \
  && cd qle \
  && make -j ${num_cores} \
  && make install \
```
The ```cd qle``` before install sorts out my problems. I'm going to copy that across to my ```Dockerfile```.

Cheers

**Comment by QuaternionRisk** [comment]
Great stuff, thanks for the cmake heads up.
