### ISSUE TITLE
OREAnalytics not building

### ISSUE THREAD

**Issue by ckoudell100** [OpenSourceRisk/Engine#32]
I am trying to build the ORE suite but am hitting a build error in solution OREAnalytics postprocess.cpp due to some undeclared identifiers. I could probably fix this for you, but am not sure this is the right thing to do. Can you have a look please? Thanks.

**Comment by QuaternionRisk** [comment]
Yes, the head has some compile errors right now, the release tags are fine though. We are working on a v4 release and will have it all working soon, hopefully we will start pushing to head this week.

**Comment by byouness** [comment]
With release v1.8.4.1 I still have a build issue with postprocess.cpp, I am using:
- Boost 1.70
- QuantLib-1.15

```
(...)\engine-1.8.4.1\oreanalytics\orea\aggregation\postprocess.cpp(1105):` error C2664:
std::vector<boost::function1<QuantLib::Real,QuantLib::Array>,std::allocator<_Ty>>::vector(const std::vector<_Ty,std::allocator<_Ty>> &)':
cannot convert argument 1 from 'std::vector<boost::function<QuantLib::Real (QuantLib::Array)>,std::allocator<_Ty>>' to 'const _Alloc &'
        with
        [
            _Ty=boost::function1<QuantLib::Real,QuantLib::Array>
        ]
        and
        [
            _Ty=boost::function<QuantLib::Real (QuantLib::Array)>
        ]
        and
        [
            _Alloc=std::allocator<boost::function1<QuantLib::Real,QuantLib::Array>>
        ]

(...)

note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called.
```

**Comment by byouness** [comment]
Somehow, replacing those lines:
https://github.com/OpenSourceRisk/Engine/blob/742b60f059c555bc38143af5beda3176ff6f7cf4/OREAnalytics/orea/aggregation/postprocess.cpp#L1102-L1107
with 
```
std::vector<ext::function<Real(Array)>> v(
    LsmBasisSystem::multiPathBasisSystem(regressionDimension, polynomOrder, polynomType));
```
fixed it for me.

I don't understand why since 0x011500f0 (i.e. QL 1.15 hex version) > 0x01150000 is true...

**Comment by rkapl123** [comment]
The actual issue is that postprocess.cpp (and QuantExt\test\stabilisedglls.cpp as well by the way) have no idea of the QL_HEX_VERSION, which is included in version.hpp. There is one more place (C:\dev\ORE\trunk\OREData\ored\portfolio\legdata.cpp) where QL_HEX_VERSION is used, but here version.hpp is included, so it works). I've added version.hpp to these two files and make a pull request (along with allowing ORE to compile with VS 2019 and the latest Quantlib -> french calendar is now in Quantlib!).

-regards,
Roland

**Comment by pcaspers** [comment]
@ckoudell100 can this be closed?

**Comment by QuaternionRisk** [comment]
We have updated master approaching the 7th release. I assume we can close this issue. Please open a new one for release 7 if issues persist.
