### ISSUE TITLE
Examples can't be run in current master

### ISSUE THREAD

**Issue by rkapl123** [OpenSourceRisk/Engine#50]
After pulling and compiling the new master, I can't run some examples any more (e.g. example 1). ORE stops with messages like

DEBUG    [2020-Jun-23 20:43:43.409165] (...data\yieldcurve.cpp:1401) : Adding Segment Cross Currency Basis Swap with conventions "USD-CHF-XCCY-BASIS-CONVENTIONS"
DEBUG    [2020-Jun-23 20:43:43.540667] (...tdata\yieldcurve.cpp:668) : Bootstrapping with 13 instruments
ALERT    [2020-Jun-23 20:43:43.556290] (...ata\todaysmarket.cpp:871) : StructuredErrorMessage { "errorType":"Curve", "curveId":"Yield/CHF/CHF-IN-USD", "exceptionType":"Failed to Build Curve", "exceptionMessage":"yield curve building failed for curve CHF-IN-USD on date 2016-02-05: 1st iteration: failed at 5th alive instrument, pillar February 9th, 2018, maturity February 9th, 2018, reference date February 5th, 2016: 1st leg: no implementation provided"}

final message: ALERT    [2020-Jun-23 20:43:49.742852] (...\orea\app\oreapp.cpp:231) : Error: Cannot build all required curves! Building failed for: (Yield/CHF/CHF-IN-EUR: yield curve building failed for curve CHF-IN-EUR on date 2016-02-05: 1st iteration: failed at 3rd alive instrument, pillar February 9th, 2018, maturity February 9th, 2018, reference date February 5th, 2016: 1st leg: no implementation provided); (Yield/CHF/CHF-IN-USD: yield curve building failed for curve CHF-IN-USD on date 2016-02-05: 1st iteration: failed at 5th alive instrument, pillar February 9th, 2018, maturity February 9th, 2018, reference date February 5th, 2016: 1st leg: no implementation provided); (Yield/GBP/GBP-IN-EUR: yield curve building failed for curve GBP-IN-EUR on date 2016-02-05: 1st iteration: failed at 5th alive instrument, pillar February 9th, 2018, maturity February 9th, 2018, reference date February 5th, 2016: 1st leg: no implementation provided); (Yield/GBP/GBP-IN-USD: yield curve building failed for curve GBP-IN-USD on date 2016-02-05: 1st iteration: failed at 5th alive instrument, pillar February 9th, 2018, maturity February 9th, 2018, reference date February 5th, 2016: 1st leg: no implementation provided); 

-regards,
Roland

**Comment by pcaspers** [comment]
Hi Roland, the master was just updated, can you pull again and check?

**Comment by rkapl123** [comment]
I pulled it and it works perfectly now. everything fine on Visual Studio 2019!

-regards,
Roland
