### ISSUE TITLE
Manual: missing entry in table for "Exposure Simulation & XVA" for CPI Caps/Floors

### ISSUE THREAD

**Issue by mcraveiro** [OpenSourceRisk/Engine#52]
Hi ORE developers,

Many thanks for an amazing open source project and for the new release. I'd like to report a very minor issue with the manual, but I wasn't sure what the correct fix was, so I didn't create a PR. In ```Docs/UserGuide/userguide.tex```:

```
CPI Swaps & Y & Y & N & Y \\
\hline
CPI Caps/Floors & Y & Y & N \\
```
CPI Caps/Floors is missing the last column I believe (e.g. ```CPI Caps/Floors & Y & Y & N & N \\``` or ```CPI Caps/Floors & Y & Y & N & Y \\```).

Cheers

**Comment by rkapl123** [comment]
I think this has been addressed in the current version.

**Comment by mcraveiro** [comment]
Ah excellent, thanks @rkapl123. I'll close the ticket then.
