### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by laurent101** [OpenSourceRisk/Engine#56]
Hi,
I've built ORE 1.8.5 on Ubuntu 20.04. No problems compiling and linking ORE. However, when running the test-suite for e.g. QuantExt, I end up with the following error:

./quantext-test-suite: symbol lookup error: /home/ore108050/build/QuantExt/qle/libQuantExt.so: undefined symbol: _ZN8QuantLib21DiscountingSwapEngineC1ERKNS_6HandleINS_18YieldTermStructureEEEN5boost8optionalIbEENS_4DateES9_

This function is indeed not defined in libQuantExt.so but in libQuantLib.so. 

Has anyone experienced a similar problem on Linux? 

Thanks in advance for any assistance.

**Comment by pcaspers** [comment]
Hi, is it possible that you have a second QuantLib library installed? What is the value of the environment variable LD_LIBRARY_PATH and what happens if you set this variable to point at the folder where the QuantLib library built together with ORE is located?

**Comment by laurent101** [comment]
Hi Peter, thanks for the swift reply and the useful hint. Indeed, I have a second QL library installed, and, because it is the same QL release 1.18 as the one used in ORE 1.8.5 (as of 24 June 2020), I had added a second path to LD_LIBRARY_PATH, pointing explicitly to ORE’s QL library. That seemingly caused a name conflict. After removing the lib path pointing to ORE’s QL library the ORE test-suite passed without errors.

What I have yet to test/work out is to build both QL-SWIG and ORE-SWIG using Python setup.py with all libraries installed and paths set in LD_LIBRARY_PATH.

Again, thanks for the assistance.

**Comment by laurent101** [comment]
Yes, issue sorted. Thanks
