### ISSUE TITLE
9.6 Money Market Futures Price amendment

### ISSUE THREAD

**Issue by Borgomi42** [OpenSourceRisk/Engine#6]
9.6. states that 
1) 
the definition of the futures includes 5 Tokens. However in ORE 6 are expected. The sixth one is the tenor.
So MM FUTURE/PRICE/EUR/JUN18/LIF3ME would be MM FUTURE/PRICE/EUR/JUN18/LIF3ME/3M
2) 
it states "Expiry month is typically quoted as JUN08, SEP09, DEC10,". However, YYYY-MM is expected.

Best Regards
Borgomi

**Comment by QuaternionRisk** [comment]
Thanks for the heads-up, this will be fixed in the next release.

**Comment by pcaspers** [comment]
@Borgomi42 this is fixed, can you check and close this issue?

**Comment by Borgomi42** [comment]
Thanks
