### ISSUE TITLE
Issue with QuantExt build

### ISSUE THREAD

**Issue by azh-coder** [OpenSourceRisk/Engine#62]
Hello Everyone,

I followed the user_guide https://www.opensourcerisk.org/wp-content/uploads/2020/06/userguide.pdf
to build ORE on my machine and I am having an issue in the second stage after building Quantlib (a successfully build), I have provided a screenshot for the Property page and the error itself. I would appreciate any help I can get. 

![pro1](https://user-images.githubusercontent.com/77345189/104345554-7bae1580-54cc-11eb-8435-8e78144496f4.png)
![pro2](https://user-images.githubusercontent.com/77345189/104345576-823c8d00-54cc-11eb-9bdd-04002d82a937.png)
![error](https://user-images.githubusercontent.com/77345189/104345593-88cb0480-54cc-11eb-81e2-c60b7fa2fdf9.png)

**Comment by azh-coder** [comment]
As a follow-up, i am using boost_1_75_0, QuantLib-1.18, and ORE-1.8.5.

**Comment by rkapl123** [comment]
Can you check the path in additional include folders under C/C++? It should contain the current folder (.)
![Screenshot 2021-01-12 192231 PNG](https://user-images.githubusercontent.com/7430763/104356063-c8651100-550b-11eb-87a9-ce7b4b8a356a.jpg)

**Comment by azh-coder** [comment]
![pro3](https://user-images.githubusercontent.com/77345189/104360709-7e663600-54df-11eb-974f-2a2891d0d24c.png)

**Comment by pcaspers** [comment]
It looks you customised the paths thereby breaking the build. It's better to add the boost paths to the property pages bound to the machine rather than changing the ORE project files (as per the user guide).

**Comment by azh-coder** [comment]
I tried with every possible path, the issue is still there.

**Comment by pcaspers** [comment]
When you say every possible path, does that include the original path in the distribution? As I said, it's not necessary to change this, you can add the boost include and library paths to your machine property file without touching the project files.

**Comment by rkapl123** [comment]
> 
> 
> I tried with every possible path, the issue is still there.

So, does your Include Directory have the current path (a dot (".") somewhere)?

**Comment by QuaternionRisk** [comment]
I'll close the issue now. Please open a new one if the issue still persists.
