### ISSUE TITLE
The problem of ORE-SWIG

### ISSUE THREAD

**Issue by catdrinkcola** [OpenSourceRisk/Engine#65]
The Quantext Python library is successfully generated by swig in Windows system,But when I ran the test file, I encountered the following error：
testing QuantExt 1.8.5.0
testConsistency (instruments.FxForwardTest)
Test consistency of fair price and NPV() ... oks
testSimpleInspectors (instruments.FxForwardTest)
Test FxForward simple inspectors. ... ok
testConsistency (instruments.DepositTest)
Test consistency of fair price and NPV() ... ok
testSimpleInspectors (instruments.DepositTest)
Test Deposit simple inspectors. ... ok
testConsistency (instruments.EquityForwardTest)
Test consistency of fair price and NPV() ... ok
testSimpleInspectors (instruments.EquityForwardTest)
Test EquityForward simple inspectors. ... ok
testConsistency (instruments.TenorBasisSwapTest)
Test consistency of fair price and NPV() ... ERROR
testSchedules (instruments.TenorBasisSwapTest)
Test TenorBasisSwap schedules. ... ERROR
testSimpleInspectors (instruments.TenorBasisSwapTest)
Test TenorBasisSwap simple inspectors. ... ERROR
testConsistency (instruments.SubPeriodsSwapTest)
Test consistency of fair price and NPV() ... ERROR
testSchedules (instruments.SubPeriodsSwapTest)
Test SubPeriodsSwap schedules. ... ERROR
testSimpleInspectors (instruments.SubPeriodsSwapTest)
Test SubPeriodsSwap simple inspectors. ... ERROR
testNPV (instruments.CommodityForwardTest)
Test NPV() ... ok
testSimpleInspectors (instruments.CommodityForwardTest)
Test CommodityForward simple inspectors. ... ok
testConsistency (instruments.PaymentTest)
Test consistency of fair price and NPV() ... ok
testSimpleInspectors (instruments.PaymentTest)
Test Payment simple inspectors. ... swig/python detected a memory leak of type 'QuantLib::ext::shared_ptr< SimpleCashFlow > *', no destructor found.
ERROR
testConsistency (instruments.CrossCurrencyFixFloatSwapTest)
Test consistency of fair price and NPV() ... ERROR
testSchedules (instruments.CrossCurrencyFixFloatSwapTest)
Test CrossCurrencyFixFloatSwap schedules. ... ERROR
testSimpleInspectors (instruments.CrossCurrencyFixFloatSwapTest)
Test CrossCurrencyFixFloatSwap simple inspectors. ... ERROR
testConsistency (instruments.AverageOISTest)
Test consistency of fair price and NPV() ... ERROR
testSimpleInspectors (instruments.AverageOISTest)
Test AverageOIS simple inspectors. ... ERROR
testSimpleInspectors (ratehelpers.AverageOISRateHelpersTest)
Test Avegare OIS Rate helpers simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.CrossCcyBasisSwapHelperTest)
Test Cross Curency Basis Swap Helper simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.TenorBasisSwapHelperTest)
Test Tenor Basis Swap Helper simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.SubPeriodsSwapHelperTest)
Test SubPeriods Basis Swap Helper simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.OIBSHelperTest)
Test OIBS Helper simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.BasisTwoSwapHelperTest)
Test basis to swap Helper simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.OICCBSHelperTest)
Test OICCBS simple inspector. ... ERROR
testSimpleInspectors (ratehelpers.ImmFraRateHelperTest)
Test  ImmFraRateHelper simple inspector ... ERROR
testSimpleInspectors (ratehelpers.CrossCcyFixFloatSwapHelperTest)
Test crossccyfixfloat rate helper simple inspector ... ERROR
testConsistency (cashflow.FXLinkedCashFlowTest)
Test consistency of FX Linked Cash Flow fair price and NPV() ... ERROR
testSimpleInspectors (cashflow.FXLinkedCashFlowTest)
Test FX Linked Cash simple inspectors. ... ERROR
testConsistency (cashflow.FloatingRateFXLinkedNotionalCouponTest)
Test consistency of FX Linked Cash Flow fair price and NPV() ... ERROR
testSimpleInspectors (cashflow.FloatingRateFXLinkedNotionalCouponTest)
Test Floating Rate FX Linked Notional Coupon inspectors. ... ERROR
testConsistency (instruments.OvernightIndexedBasisSwapTest)
Test consistency of fair price and NPV() ... ERROR
testSchedules (instruments.OvernightIndexedBasisSwapTest)
Test OvernightIndexedBasisSwap schedules. ... ERROR
testSimpleInspectors (instruments.OvernightIndexedBasisSwapTest)
Test OvernightIndexedBasisSwap simple inspectors. ... ERROR
testConsistency (instruments.OvernightIndexedCrossCcyBasisSwapTest)
Test consistency of fair price and NPV() ... ERROR
testSchedules (instruments.OvernightIndexedCrossCcyBasisSwapTest)
Test OvernightIndexedCrossCcyBasisSwap schedules. ... ERROR
testSimpleInspectors (instruments.OvernightIndexedCrossCcyBasisSwapTest)
Test OvernightIndexedCrossCcyBasisSwap and engine simple inspectors. ... ERROR
testConsistency (instruments.CreditDefaultSwapTest)
Test consistency of fair price and NPV() ... ok
testSimpleInspectors (instruments.CreditDefaultSwapTest)
Test CreditDefaultSwap simple inspectors. ... ok
testConsistency (instruments.CDSOptionTest)
Test consistency of fair price and NPV() ... ERROR
testSimpleInspectors (instruments.CDSOptionTest)
Test CDSOptionTest simple inspectors. ... ERROR
testConsistency (instruments.CrossCcyBasisSwapTest)
Test consistency of fair price and NPV() ... ERROR
testSchedules (instruments.CrossCcyBasisSwapTest)
Test CrossCcyBasisSwap schedules. ... ERROR
testSimpleInspectors (instruments.CrossCcyBasisSwapTest)
Test CrossCcyBasisSwap simple inspectors. ... ERROR
testConsistency (instruments.DiscountingSwapEngineMultiCurveTest)
Test consistency of NPV() ... ok
testSimpleInspectors (termstructures.BlackVolatilityWithATMTest)
Test Black Volatility with ATM simple inspector. ... ERROR
testSimpleInspectors (termstructures.BlackVarianceSurfaceMoneynessSpotTest)
Test Black Variance Surface Moneyness Spot simple inspector. ... ok
testSimpleInspectors (termstructures.BlackVarianceSurfaceMoneynessForwardTest)
Test Black Variance Surface Moneyness Forward simple inspector. ... ok
testSimpleInspectors (termstructures.SwapConventionsTest)
Test SwapConventions simple inspectors. ... ERROR
testSimpleInspectors (termstructures.SwaptionVolCubeWithATMTest)
Test Swaption Vol Cube With ATM simple inspector. ... ERROR
testSimpleInspectors (termstructures.QLESwaptionVolCube2Test)
Test  QLE Swaption Vol Cube 2 simple inspector. ... ERROR
testSimpleInspectors (termstructures.SwaptionVolatilityConstantSpreadTest)
Test Swaption Volatility Constant Spread simple inspector. ... ok
testSimpleInspectors (termstructures.FxBlackVannaVolgaVolatilitySurfaceTest)
Test Fx Black Vanna Volga Volatility Surface simple inspector. ... ok
...................
----------------------------------------------------------------------
Ran 56 tests in 0.381s

FAILED (errors=40)

After a period of exploration, I found that the possible parameters are boost:: shared_ ptr can lead to errors,Could you please take look at it and help me solve this problem?

**Comment by catdrinkcola** [comment]
All boost:: shared_ ptr in qle_XXX.i becomes ext:: shared_ ptr can solve this error

**Comment by QuaternionRisk** [comment]
Thanks fore the update. The SWIG wrappers have evolved in the meantime, and we changed to ext::shared_ptr where necessary to make the wrappers build on Windows. So I'll close the issue now. Please check out the latest version of ORE and ORE-SWIG by cloning the repos. Release bundles will follow next month.
