### ISSUE TITLE
OREDataTestSuite missing headers and filter

### ISSUE THREAD

**Issue by gbfredrik** [OpenSourceRisk/Engine#72]
Hi,
The OREDataTestSuite project is missing a header filter and also the inclusion of related headers in Visual Studio. I believe this may be a plausible cause for some tests not failing correctly in VS's test suite after we had done some otherwise test-breaking changes on our fork. Missing header file includes also seem to be largely present in the OREAnalytics and QuantExt projects as well. The missing files and filter also complicate adding more tests, which I don't think is intended. 

I'll strive to submit a fix for this in short, unless anyone else gets there first.

**Comment by pcaspers** [comment]
@gbfredrik is this still an issue (I assume no?)

**Comment by gbfredrik** [comment]
Ah, I didn't have time to check this earlier today. Looks fine now, no more headers in OREData/tests and the other test suites have them correctly added. Thanks!
