### ISSUE TITLE
QuantLib::DateGeneration /ql/time/dategenerationrule.hpp does not have ORE schedules!!!

### ISSUE THREAD

**Issue by mrslezak** [OpenSourceRisk/Engine#84]
Anyhow on the testsuite the issues seem to be mostly around missing semicolons and then dategeneration.cpp has quite a few calendars that are not members of QuantLib::DateGeneration such as: 

Error	C2039	'ThirdThursday': is not a member of 'QuantLib::DateGeneration'	QuantExtTestSuite	c:\engine\quantext\test\dategeneration.cpp	83
Same thing for ThirdFriday, MondayAfterThirdFriday and TuesdayAfterThirdFriday, basically everything in that dategeneration.cpp 

This leads me to believe the QuantLib dategenerationrule.hpp file (they did not include) that ORE is using is a modified version, as the mentioned rules are not inside the latest file.  Does anyone have the file with these undeclared calendar rules???  You can see the latest file is missing all of these rules: https://github.com/lballabio/QuantLib/blob/master/ql/time/dategenerationrule.hpp

**Comment by pcaspers** [comment]
duplicate to #83?

**Comment by mrslezak** [comment]
Yes thanks for clarifying the modified file which I should be able to trace the other modded QL files from.  I'll close this, thanks.
