### ISSUE TITLE
CapFloorVolatility indexing is too limiting

### ISSUE THREAD

**Issue by gbfredrik** [OpenSourceRisk/Engine#88]
Hi all,
We run portfolios of caps and floors where there may be underlyings of different IBOR indices, e.g. we may have both EUR-3M and EUR-6M surfaces. Unfortunately, this is not supported by ORE. 

The current setup has cap/floor volatilities indexed by their currencies in _todaysmarket.xml_, preventing the use of IBOR-specific naming.  We suggest a change to this such that other names may be provided, as with i.e. IndexForwardingCurves or YieldCurves, and not just currency codes. This requires changes in the pricing engine builder for caps/floors and a few other places where the volatilities are looked up from the market. 

To illustrate, this:
`<CapFloorVolatility currency="EUR">CapFloorVolatility/EUR/EUR_CF_N_3M</CapFloorVolatility>`
would become this:
`<CapFloorVolatility name="EUR-3M">CapFloorVolatility/EUR/EUR_CF_N_3M</CapFloorVolatility>`

I will update this issue if I ever find the time to implement this myself, should this be a desired feature. Maintaining backward compatibility is probably preferable if this is to be supported, so some care should be taken to ensure this. 

Best regards,
Fredrik Gerdin Börjesson,
SEB

**Comment by pcaspers** [comment]
Hi Fredrik, the next release will contain extensions for cap and swaption vol surfaces so that they can be keyed by the underlying index. We will also support OIS indices.

**Comment by gbfredrik** [comment]
Hi Peter, thanks for the update! That's great to hear, my team is very appreciative :)

**Comment by gbfredrik** [comment]
@pcaspers Looks like this issue is also resolved through 514889787bd933beaaeb00bfbad799ba01270a9d, correct? Great if so!

**Comment by pcaspers** [comment]
yes, IR cap and swaption surfaces can now be indexed by ibor/ois indices in addition to currencies

it's not achieved through this single commit only, but yes, the issue can be closed

**Comment by gbfredrik** [comment]
Super, glad to hear!
