### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by AlessandroGnoatto** [OpenSourceRisk/Engine#9]
Hi, I am trying to install ORE. However, I came up with an issue that I am not able to solve:

I work with Osx Sierra. I obtained Boost via homebrew and Boost is located at

/usr/local/Cellar/boost/1.64.0_1/include/
/usr/local/Cellar/boost/1.64.0_1/lib

I can successfully build Quantlib and QuantExt. 

./autogen.sh

./configure.sh --with-boost-include=/usr/local/Cellar/boost/1.64.0_1/include –with-boost-lib=/usr/local/Cellar/boost/1.64.0_1/lib

make -j4

Also quantext-test-suite succeeds. Now when I repeat the same for OREdata everything seems to work

checking for Boost development files... yes
checking for Boost version >= 1.55... yes
checking for Boost::uBLAS support... yes
checking for Boost unit-test framework... yes
checking whether Boost unit-test streams work... yes

however, when I run ./test/ored-test-suite

I see the error message:

Running 35 test cases...
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost16re_detail_10620013get_mem_blockEv
  Referenced from: /Users/Alessandro/ore/OreData/ored/.libs/libOREData-1.8.2.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN5boost16re_detail_10620013get_mem_blockEv
  Referenced from: /Users/Alessandro/ore/OreData/ored/.libs/libOREData-1.8.2.dylib
  Expected in: flat namespace

unknown location:0: fatal error: in "OREDataTestSuite/ParseTest/ParseTest__testStrikeParsing": signal: SIGABRT (application abort requested)

 OREData tests completed in 1 s

*** 1 failure is detected in the test module "Master Test Suite"

Any suggestion on how I can fix this? Thank you very much!

**Comment by QuaternionRisk** [comment]
Can you try to set your dyld path like this

```export DYLD_LIBRARY_PATH=/usr/local/Cellar/boost/1.64.0_1/lib:$DYLD_LIBRARY_PATH```

Does that change anything?

**Comment by AlessandroGnoatto** [comment]
That solved the issue, thank you for the prompt answer!
