### ISSUE TITLE
ISDA CDS pricing engine support

### ISSUE THREAD

**Issue by gbfredrik** [OpenSourceRisk/Engine#91]
Hi all!
This issue is to discuss the `CreditDefaultSwap` instrument available both in QuantLib and QuantExt. The version present in the latter project has additional options for the protection payment time, toggleable through an enum rather than a boolean as in QL. Because the instrument class has been duplicated, we cannot directly link the `IsdaCdsEngine` available in QL without first altering it to fit the QuantExt CDS instrument used in ORE. 

I would propose bringing these changes over to QuantLib as a small initial migration, relating to #83, along with the QuantExt `MidPointCdsEngine`. Doing so, we can avoid having to copy over the Isda engine to QuantExt as well, which we have had to do now. We will provide a PR with this setup though I am hoping for someone to provide som input on this, such that it may be resolved properly ahead of the next release. What are your thoughts on this?

Best regards,
Fredrik Gerdin Börjesson,
SEB

**Comment by pcaspers** [comment]
Yes that makes sense.

**Comment by pcaspers** [comment]
Yes this makes sense. We'll reconcile the current version of CreditDefaultSwap in QuantExt on our current dev master vs. QuantLib and align the two, so that once we've upgraded the QuantLib submodule we can eventually remove the QuantExt version.

**Comment by pcaspers** [comment]
internal dev ticket QPR-11180
