### ISSUE TITLE
Incorrect npv currency flag on FX forwards

### ISSUE THREAD

**Issue by gbfredrik** [OpenSourceRisk/Engine#93]
Hi,
We have looked into FX forwards (NDFs) recently and believe that the `npvCurrency_` variable is sometimes incorrect when a settlement currency is set and the payment date is different from the fixing date. This leads to the npv report writing the wrong currency code for the trade's npv and thus the base currency npv is incorrectly converted. 

It seems this https://github.com/OpenSourceRisk/Engine/blob/347f7d81b1991b5b88522e6e4793e82ddfe9be09/OREData/ored/portfolio/fxforward.cpp#L92 should have some adjustment to reflect the specific scenario. I will see if I can replicate the observed issue with a unit test to evaluate a fix soon. 

Best,
Fredrik Gerdin Börjesson,
SEB

**Comment by pcaspers** [comment]
Hi Fredrik, you are right. We've fixed that in our dev branch already, i.e. it will be part of the next release or update of the master branch on github.

**Comment by gbfredrik** [comment]
@pcaspers Would I be correct in saying that 2a1f7538f1dec45896dfb465e9cab1f9e2dd6e18 fixed this issue? In that case we can close this.

**Comment by pcaspers** [comment]
Yes correct!
