### ISSUE TITLE
orphaned source files dategrid.hpp/dategrid.cpp

### ISSUE THREAD

**Issue by rkapl123** [OpenSourceRisk/Engine#94]
Hi, when browsing the source code I came across two files that seem to have moved from the analytics layer (`orea/simulation/dategrid.hpp resp. dategrid.cpp`) to the data layer (`ored/utilities/dategrid.hpp resp. dategrid.cpp`)

There is still one reference to the old location in orea/scenario/scenariogeneratordata.hpp with `boost::shared_ptr<ore::analytics::DateGrid> closeOutDateGrid() const { return closeOutDateGrid_; }` and 
`private: boost::shared_ptr<ore::analytics::DateGrid> closeOutDateGrid_;`

This member doesn't seem to have much use in the project however. Removing the `ore::analytics::` qualifier didn't hurt though.

**Comment by pcaspers** [comment]
Hi Roland, you are right. Would you open a MR with a fix? I believe what probably happens is that we import the ore::data namespace into ore::analytics (a bad habit...), so that the latter namespace qualification will work as well. Thanks! Peter

**Comment by pcaspers** [comment]
@rkapl123 this is fixed right, can we close this ticket?

**Comment by rkapl123** [comment]
Seems to be all fixed now!
Regards,
Roland
